// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/Credito.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EntryPoints.GRPc.Protos {

  /// <summary>Holder for reflection information generated from Proto/Credito.proto</summary>
  public static partial class CreditoReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/Credito.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CreditoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQcm90by9DcmVkaXRvLnByb3RvEghjcmVkaXRvcxoZZ29vZ2xlL3Byb3Rv",
            "YnVmL2FueS5wcm90byJ4ChNDcmVhclVzdWFyaW9SZXF1ZXN0Eg4KBk5vbWJy",
            "ZRgBIAEoCRIQCghBcGVsbGlkbxgCIAEoCRIOCgZDZWR1bGEYAyABKAkSDgoG",
            "Q29ycmVvGAQgASgJEgwKBEVkYWQYBSABKAUSEQoJUHJvZmVzaW9uGAYgASgJ",
            "ImUKE0NyZWFyQ3JlZGl0b1JlcXVlc3QSEQoJdXN1YXJpb0lkGAIgASgJEhAK",
            "CGN1ZW50YUlkGAMgASgJEhUKDXRvdGFsUHJlc3RhbW8YBCABKAUSEgoKZGV1",
            "ZGFUb3RhbBgFIAEoBSJWChBTdGFuZGFyZFJlc3BvbnNlEiIKBGRhdGEYASAB",
            "KAsyFC5nb29nbGUucHJvdG9idWYuQW55Eg0KBWVycm9yGAIgASgIEg8KB21l",
            "c3NhZ2UYAyABKAkieAoHVXN1YXJpbxIKCgJpZBgBIAEoCRIOCgZOb21icmUY",
            "AiABKAkSEAoIQXBlbGxpZG8YAyABKAkSDgoGQ2VkdWxhGAQgASgJEg4KBkNv",
            "cnJlbxgFIAEoCRIMCgRFZGFkGAYgASgFEhEKCVByb2Zlc2lvbhgHIAEoCSJl",
            "CgdDcmVkaXRvEgoKAmlkGAEgASgJEhEKCXVzdWFyaW9JZBgCIAEoCRIQCghj",
            "dWVudGFJZBgDIAEoCRIVCg10b3RhbFByZXN0YW1vGAQgASgFEhIKCmRldWRh",
            "VG90YWwYBSABKAUyqAEKEFVzdWFyaW9zU2VydmljZXMSSQoMQ3JlYXJVc3Vh",
            "cmlvEh0uY3JlZGl0b3MuQ3JlYXJVc3VhcmlvUmVxdWVzdBoaLmNyZWRpdG9z",
            "LlN0YW5kYXJkUmVzcG9uc2USSQoMQ3JlYXJDcmVkaXRvEh0uY3JlZGl0b3Mu",
            "Q3JlYXJDcmVkaXRvUmVxdWVzdBoaLmNyZWRpdG9zLlN0YW5kYXJkUmVzcG9u",
            "c2VCGqoCF0VudHJ5UG9pbnRzLkdSUGMuUHJvdG9zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.CrearUsuarioRequest), global::EntryPoints.GRPc.Protos.CrearUsuarioRequest.Parser, new[]{ "Nombre", "Apellido", "Cedula", "Correo", "Edad", "Profesion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.CrearCreditoRequest), global::EntryPoints.GRPc.Protos.CrearCreditoRequest.Parser, new[]{ "UsuarioId", "CuentaId", "TotalPrestamo", "DeudaTotal" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.StandardResponse), global::EntryPoints.GRPc.Protos.StandardResponse.Parser, new[]{ "Data", "Error", "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.Usuario), global::EntryPoints.GRPc.Protos.Usuario.Parser, new[]{ "Id", "Nombre", "Apellido", "Cedula", "Correo", "Edad", "Profesion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.Credito), global::EntryPoints.GRPc.Protos.Credito.Parser, new[]{ "Id", "UsuarioId", "CuentaId", "TotalPrestamo", "DeudaTotal" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Requests
  /// </summary>
  public sealed partial class CrearUsuarioRequest : pb::IMessage<CrearUsuarioRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrearUsuarioRequest> _parser = new pb::MessageParser<CrearUsuarioRequest>(() => new CrearUsuarioRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CrearUsuarioRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.CreditoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CrearUsuarioRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CrearUsuarioRequest(CrearUsuarioRequest other) : this() {
      nombre_ = other.nombre_;
      apellido_ = other.apellido_;
      cedula_ = other.cedula_;
      correo_ = other.correo_;
      edad_ = other.edad_;
      profesion_ = other.profesion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CrearUsuarioRequest Clone() {
      return new CrearUsuarioRequest(this);
    }

    /// <summary>Field number for the "Nombre" field.</summary>
    public const int NombreFieldNumber = 1;
    private string nombre_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nombre {
      get { return nombre_; }
      set {
        nombre_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Apellido" field.</summary>
    public const int ApellidoFieldNumber = 2;
    private string apellido_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Apellido {
      get { return apellido_; }
      set {
        apellido_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Cedula" field.</summary>
    public const int CedulaFieldNumber = 3;
    private string cedula_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cedula {
      get { return cedula_; }
      set {
        cedula_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Correo" field.</summary>
    public const int CorreoFieldNumber = 4;
    private string correo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Correo {
      get { return correo_; }
      set {
        correo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Edad" field.</summary>
    public const int EdadFieldNumber = 5;
    private int edad_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Edad {
      get { return edad_; }
      set {
        edad_ = value;
      }
    }

    /// <summary>Field number for the "Profesion" field.</summary>
    public const int ProfesionFieldNumber = 6;
    private string profesion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Profesion {
      get { return profesion_; }
      set {
        profesion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CrearUsuarioRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CrearUsuarioRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Nombre != other.Nombre) return false;
      if (Apellido != other.Apellido) return false;
      if (Cedula != other.Cedula) return false;
      if (Correo != other.Correo) return false;
      if (Edad != other.Edad) return false;
      if (Profesion != other.Profesion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Nombre.Length != 0) hash ^= Nombre.GetHashCode();
      if (Apellido.Length != 0) hash ^= Apellido.GetHashCode();
      if (Cedula.Length != 0) hash ^= Cedula.GetHashCode();
      if (Correo.Length != 0) hash ^= Correo.GetHashCode();
      if (Edad != 0) hash ^= Edad.GetHashCode();
      if (Profesion.Length != 0) hash ^= Profesion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Nombre.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nombre);
      }
      if (Apellido.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Apellido);
      }
      if (Cedula.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Cedula);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Correo);
      }
      if (Edad != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Edad);
      }
      if (Profesion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Profesion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Nombre.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Nombre);
      }
      if (Apellido.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Apellido);
      }
      if (Cedula.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Cedula);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Correo);
      }
      if (Edad != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Edad);
      }
      if (Profesion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Profesion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Nombre.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nombre);
      }
      if (Apellido.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Apellido);
      }
      if (Cedula.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cedula);
      }
      if (Correo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Correo);
      }
      if (Edad != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Edad);
      }
      if (Profesion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Profesion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CrearUsuarioRequest other) {
      if (other == null) {
        return;
      }
      if (other.Nombre.Length != 0) {
        Nombre = other.Nombre;
      }
      if (other.Apellido.Length != 0) {
        Apellido = other.Apellido;
      }
      if (other.Cedula.Length != 0) {
        Cedula = other.Cedula;
      }
      if (other.Correo.Length != 0) {
        Correo = other.Correo;
      }
      if (other.Edad != 0) {
        Edad = other.Edad;
      }
      if (other.Profesion.Length != 0) {
        Profesion = other.Profesion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Nombre = input.ReadString();
            break;
          }
          case 18: {
            Apellido = input.ReadString();
            break;
          }
          case 26: {
            Cedula = input.ReadString();
            break;
          }
          case 34: {
            Correo = input.ReadString();
            break;
          }
          case 40: {
            Edad = input.ReadInt32();
            break;
          }
          case 50: {
            Profesion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Nombre = input.ReadString();
            break;
          }
          case 18: {
            Apellido = input.ReadString();
            break;
          }
          case 26: {
            Cedula = input.ReadString();
            break;
          }
          case 34: {
            Correo = input.ReadString();
            break;
          }
          case 40: {
            Edad = input.ReadInt32();
            break;
          }
          case 50: {
            Profesion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CrearCreditoRequest : pb::IMessage<CrearCreditoRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrearCreditoRequest> _parser = new pb::MessageParser<CrearCreditoRequest>(() => new CrearCreditoRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CrearCreditoRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.CreditoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CrearCreditoRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CrearCreditoRequest(CrearCreditoRequest other) : this() {
      usuarioId_ = other.usuarioId_;
      cuentaId_ = other.cuentaId_;
      totalPrestamo_ = other.totalPrestamo_;
      deudaTotal_ = other.deudaTotal_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CrearCreditoRequest Clone() {
      return new CrearCreditoRequest(this);
    }

    /// <summary>Field number for the "usuarioId" field.</summary>
    public const int UsuarioIdFieldNumber = 2;
    private string usuarioId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UsuarioId {
      get { return usuarioId_; }
      set {
        usuarioId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cuentaId" field.</summary>
    public const int CuentaIdFieldNumber = 3;
    private string cuentaId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CuentaId {
      get { return cuentaId_; }
      set {
        cuentaId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "totalPrestamo" field.</summary>
    public const int TotalPrestamoFieldNumber = 4;
    private int totalPrestamo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TotalPrestamo {
      get { return totalPrestamo_; }
      set {
        totalPrestamo_ = value;
      }
    }

    /// <summary>Field number for the "deudaTotal" field.</summary>
    public const int DeudaTotalFieldNumber = 5;
    private int deudaTotal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeudaTotal {
      get { return deudaTotal_; }
      set {
        deudaTotal_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CrearCreditoRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CrearCreditoRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UsuarioId != other.UsuarioId) return false;
      if (CuentaId != other.CuentaId) return false;
      if (TotalPrestamo != other.TotalPrestamo) return false;
      if (DeudaTotal != other.DeudaTotal) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UsuarioId.Length != 0) hash ^= UsuarioId.GetHashCode();
      if (CuentaId.Length != 0) hash ^= CuentaId.GetHashCode();
      if (TotalPrestamo != 0) hash ^= TotalPrestamo.GetHashCode();
      if (DeudaTotal != 0) hash ^= DeudaTotal.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UsuarioId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UsuarioId);
      }
      if (CuentaId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CuentaId);
      }
      if (TotalPrestamo != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(TotalPrestamo);
      }
      if (DeudaTotal != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DeudaTotal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UsuarioId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UsuarioId);
      }
      if (CuentaId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CuentaId);
      }
      if (TotalPrestamo != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(TotalPrestamo);
      }
      if (DeudaTotal != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DeudaTotal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UsuarioId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UsuarioId);
      }
      if (CuentaId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CuentaId);
      }
      if (TotalPrestamo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalPrestamo);
      }
      if (DeudaTotal != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeudaTotal);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CrearCreditoRequest other) {
      if (other == null) {
        return;
      }
      if (other.UsuarioId.Length != 0) {
        UsuarioId = other.UsuarioId;
      }
      if (other.CuentaId.Length != 0) {
        CuentaId = other.CuentaId;
      }
      if (other.TotalPrestamo != 0) {
        TotalPrestamo = other.TotalPrestamo;
      }
      if (other.DeudaTotal != 0) {
        DeudaTotal = other.DeudaTotal;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            UsuarioId = input.ReadString();
            break;
          }
          case 26: {
            CuentaId = input.ReadString();
            break;
          }
          case 32: {
            TotalPrestamo = input.ReadInt32();
            break;
          }
          case 40: {
            DeudaTotal = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            UsuarioId = input.ReadString();
            break;
          }
          case 26: {
            CuentaId = input.ReadString();
            break;
          }
          case 32: {
            TotalPrestamo = input.ReadInt32();
            break;
          }
          case 40: {
            DeudaTotal = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Responses
  /// </summary>
  public sealed partial class StandardResponse : pb::IMessage<StandardResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StandardResponse> _parser = new pb::MessageParser<StandardResponse>(() => new StandardResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StandardResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.CreditoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StandardResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StandardResponse(StandardResponse other) : this() {
      data_ = other.data_ != null ? other.data_.Clone() : null;
      error_ = other.error_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StandardResponse Clone() {
      return new StandardResponse(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Any data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private bool error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StandardResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StandardResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Data, other.Data)) return false;
      if (Error != other.Error) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (data_ != null) hash ^= Data.GetHashCode();
      if (Error != false) hash ^= Error.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (Error != false) {
        output.WriteRawTag(16);
        output.WriteBool(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (data_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Data);
      }
      if (Error != false) {
        output.WriteRawTag(16);
        output.WriteBool(Error);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (Error != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StandardResponse other) {
      if (other == null) {
        return;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Data.MergeFrom(other.Data);
      }
      if (other.Error != false) {
        Error = other.Error;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
          case 16: {
            Error = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
          case 16: {
            Error = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Usuario : pb::IMessage<Usuario>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Usuario> _parser = new pb::MessageParser<Usuario>(() => new Usuario());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Usuario> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.CreditoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Usuario() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Usuario(Usuario other) : this() {
      id_ = other.id_;
      nombre_ = other.nombre_;
      apellido_ = other.apellido_;
      cedula_ = other.cedula_;
      correo_ = other.correo_;
      edad_ = other.edad_;
      profesion_ = other.profesion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Usuario Clone() {
      return new Usuario(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Nombre" field.</summary>
    public const int NombreFieldNumber = 2;
    private string nombre_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nombre {
      get { return nombre_; }
      set {
        nombre_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Apellido" field.</summary>
    public const int ApellidoFieldNumber = 3;
    private string apellido_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Apellido {
      get { return apellido_; }
      set {
        apellido_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Cedula" field.</summary>
    public const int CedulaFieldNumber = 4;
    private string cedula_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cedula {
      get { return cedula_; }
      set {
        cedula_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Correo" field.</summary>
    public const int CorreoFieldNumber = 5;
    private string correo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Correo {
      get { return correo_; }
      set {
        correo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Edad" field.</summary>
    public const int EdadFieldNumber = 6;
    private int edad_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Edad {
      get { return edad_; }
      set {
        edad_ = value;
      }
    }

    /// <summary>Field number for the "Profesion" field.</summary>
    public const int ProfesionFieldNumber = 7;
    private string profesion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Profesion {
      get { return profesion_; }
      set {
        profesion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Usuario);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Usuario other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nombre != other.Nombre) return false;
      if (Apellido != other.Apellido) return false;
      if (Cedula != other.Cedula) return false;
      if (Correo != other.Correo) return false;
      if (Edad != other.Edad) return false;
      if (Profesion != other.Profesion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Nombre.Length != 0) hash ^= Nombre.GetHashCode();
      if (Apellido.Length != 0) hash ^= Apellido.GetHashCode();
      if (Cedula.Length != 0) hash ^= Cedula.GetHashCode();
      if (Correo.Length != 0) hash ^= Correo.GetHashCode();
      if (Edad != 0) hash ^= Edad.GetHashCode();
      if (Profesion.Length != 0) hash ^= Profesion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Nombre.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nombre);
      }
      if (Apellido.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Apellido);
      }
      if (Cedula.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Cedula);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Correo);
      }
      if (Edad != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Edad);
      }
      if (Profesion.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Profesion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Nombre.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nombre);
      }
      if (Apellido.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Apellido);
      }
      if (Cedula.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Cedula);
      }
      if (Correo.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Correo);
      }
      if (Edad != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Edad);
      }
      if (Profesion.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Profesion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Nombre.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nombre);
      }
      if (Apellido.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Apellido);
      }
      if (Cedula.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cedula);
      }
      if (Correo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Correo);
      }
      if (Edad != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Edad);
      }
      if (Profesion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Profesion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Usuario other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Nombre.Length != 0) {
        Nombre = other.Nombre;
      }
      if (other.Apellido.Length != 0) {
        Apellido = other.Apellido;
      }
      if (other.Cedula.Length != 0) {
        Cedula = other.Cedula;
      }
      if (other.Correo.Length != 0) {
        Correo = other.Correo;
      }
      if (other.Edad != 0) {
        Edad = other.Edad;
      }
      if (other.Profesion.Length != 0) {
        Profesion = other.Profesion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Nombre = input.ReadString();
            break;
          }
          case 26: {
            Apellido = input.ReadString();
            break;
          }
          case 34: {
            Cedula = input.ReadString();
            break;
          }
          case 42: {
            Correo = input.ReadString();
            break;
          }
          case 48: {
            Edad = input.ReadInt32();
            break;
          }
          case 58: {
            Profesion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Nombre = input.ReadString();
            break;
          }
          case 26: {
            Apellido = input.ReadString();
            break;
          }
          case 34: {
            Cedula = input.ReadString();
            break;
          }
          case 42: {
            Correo = input.ReadString();
            break;
          }
          case 48: {
            Edad = input.ReadInt32();
            break;
          }
          case 58: {
            Profesion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Credito : pb::IMessage<Credito>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Credito> _parser = new pb::MessageParser<Credito>(() => new Credito());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Credito> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.CreditoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Credito() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Credito(Credito other) : this() {
      id_ = other.id_;
      usuarioId_ = other.usuarioId_;
      cuentaId_ = other.cuentaId_;
      totalPrestamo_ = other.totalPrestamo_;
      deudaTotal_ = other.deudaTotal_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Credito Clone() {
      return new Credito(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "usuarioId" field.</summary>
    public const int UsuarioIdFieldNumber = 2;
    private string usuarioId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UsuarioId {
      get { return usuarioId_; }
      set {
        usuarioId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cuentaId" field.</summary>
    public const int CuentaIdFieldNumber = 3;
    private string cuentaId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CuentaId {
      get { return cuentaId_; }
      set {
        cuentaId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "totalPrestamo" field.</summary>
    public const int TotalPrestamoFieldNumber = 4;
    private int totalPrestamo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TotalPrestamo {
      get { return totalPrestamo_; }
      set {
        totalPrestamo_ = value;
      }
    }

    /// <summary>Field number for the "deudaTotal" field.</summary>
    public const int DeudaTotalFieldNumber = 5;
    private int deudaTotal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeudaTotal {
      get { return deudaTotal_; }
      set {
        deudaTotal_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Credito);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Credito other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (UsuarioId != other.UsuarioId) return false;
      if (CuentaId != other.CuentaId) return false;
      if (TotalPrestamo != other.TotalPrestamo) return false;
      if (DeudaTotal != other.DeudaTotal) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (UsuarioId.Length != 0) hash ^= UsuarioId.GetHashCode();
      if (CuentaId.Length != 0) hash ^= CuentaId.GetHashCode();
      if (TotalPrestamo != 0) hash ^= TotalPrestamo.GetHashCode();
      if (DeudaTotal != 0) hash ^= DeudaTotal.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (UsuarioId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UsuarioId);
      }
      if (CuentaId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CuentaId);
      }
      if (TotalPrestamo != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(TotalPrestamo);
      }
      if (DeudaTotal != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DeudaTotal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (UsuarioId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UsuarioId);
      }
      if (CuentaId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CuentaId);
      }
      if (TotalPrestamo != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(TotalPrestamo);
      }
      if (DeudaTotal != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(DeudaTotal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (UsuarioId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UsuarioId);
      }
      if (CuentaId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CuentaId);
      }
      if (TotalPrestamo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalPrestamo);
      }
      if (DeudaTotal != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeudaTotal);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Credito other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.UsuarioId.Length != 0) {
        UsuarioId = other.UsuarioId;
      }
      if (other.CuentaId.Length != 0) {
        CuentaId = other.CuentaId;
      }
      if (other.TotalPrestamo != 0) {
        TotalPrestamo = other.TotalPrestamo;
      }
      if (other.DeudaTotal != 0) {
        DeudaTotal = other.DeudaTotal;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            UsuarioId = input.ReadString();
            break;
          }
          case 26: {
            CuentaId = input.ReadString();
            break;
          }
          case 32: {
            TotalPrestamo = input.ReadInt32();
            break;
          }
          case 40: {
            DeudaTotal = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            UsuarioId = input.ReadString();
            break;
          }
          case 26: {
            CuentaId = input.ReadString();
            break;
          }
          case 32: {
            TotalPrestamo = input.ReadInt32();
            break;
          }
          case 40: {
            DeudaTotal = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
